Bienes Raices HAXA/Models/Propiedad.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bienes_Raices_HAXA.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Propiedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Propiedad()
        {
            this.Citas = new HashSet<Citas>();
            this.Imagenes = new HashSet<Imagenes>();
        }
    
        public long idPropiedad { get; set; }
        public string nombre { get; set; }
        public string provincia { get; set; }
        public string canton { get; set; }
        public string distrito { get; set; }
        public string direccion { get; set; }
        public string descripcion { get; set; }
        public int idCategoria { get; set; }
        public int idEstado { get; set; }
        public Nullable<int> pisos { get; set; }
        public Nullable<int> m2 { get; set; }
        public Nullable<int> habitacion { get; set; }
        public Nullable<int> baños { get; set; }
        public Nullable<int> garage { get; set; }
        public long idUsuario { get; set; }
        public Nullable<long> idVendedor { get; set; }
        public string precio { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Citas> Citas { get; set; }
        public virtual Estado Estado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Imagenes> Imagenes { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}

Bienes Raices HAXA/Controllers/CitasController.cs
using Bienes_Raices_HAXA.Models;
using System;
using System.Collections.Generic;
using System.Web.Mvc;

namespace Bienes_Raices_HAXA.Controllers
{
    //[VerificacionSesion]
    public class CitasController : Controller
    {
        #region Index method

        /// <summary>
        /// GET: Citas/Index method.
        /// </summary>
        /// <returns>Returns - index view page</returns>
        public ActionResult Index()
        {
            // Info.
            return this.View();
        }

        #endregion Index method

        #region Get Calendar data method.

        /// <summary>
        /// GET: /Citas/GetCalendarData
        /// </summary>
        /// <returns>Return data</returns>
        public ActionResult GetCalendarData()
        {
            // Initialization.
            JsonResult result = new JsonResult();

            try
            {
                // Loading.
                List<Citas2> data = this.LoadData();

                // Processing.
                result = this.Json(data, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                // Info
                Console.Write(ex);
            }

            // Return info.
            return result;
        }

        #endregion Get Calendar data method.

        #region Helpers

        #region Load Data

        /// <summary>
        /// Load data method.
        /// </summary>
        /// <returns>Returns - Data</returns>
        private List<Citas2> LoadData()
        {
            // Initialization.
            List<Citas2> lst = new List<Citas2>();
            CitasModel modelo = new CitasModel();
            try
            {
                var lista = modelo.GetAllHorario();

                // Read file.

                return lista;
            }
            catch (Exception ex)
            {
                // info.
                Console.Write(ex);
            }

            // info.
            return lst;
        }

        #endregion Load Data

        #endregion Helpers

        [HttpGet]
        public ActionResult AgregarCita()
        {
            return View("AgregarCita", null);
        }

        [HttpPost]
        public ActionResult AgregarCita(Citas nuevaCita, string hora)
        {
            try
            {
                object idPropiedad = Session["idPropiedad"];
                object idUsuario = Session["id"];
                CitasModel modelo = new CitasModel();
                var resultado = modelo.agregarCita(nuevaCita, idUsuario, idPropiedad, hora);
                if (resultado == true)
                {
                    return View("Index");
                }
                else
                {
                    return View("~/Views/Shared/Error.cshtml");
                }
            }
            catch (Exception ex)
            {
                return View("~/Views/Shared/Error.cshtml");
            }
        }

        public ActionResult ConsultaFechaFinal(string fechaInicio, string hora)
        {
            try
            {
                int horaFinal = Convert.ToInt32(hora);
                horaFinal = horaFinal + 2;
                string fechaHoraFinal = Convert.ToString(horaFinal) + ":" + "00:00";
                var resultado = fechaInicio + " " + fechaHoraFinal;

                return Json(resultado, JsonRequestBehavior.AllowGet);
            }
            catch (Exception)
            {
                return Json("Se presentó un error", JsonRequestBehavior.DenyGet);
            }
        }
    }
}

Bienes Raices HAXA/Controllers/HomeController.cs
using Bienes_Raices_HAXA.Models;
using System;
using System.Collections.Generic;
using System.Web;
using System.Web.Mvc;

namespace Bienes_Raices_HAXA.Controllers
{
    public class HomeController : Controller
    {
        private GestionPropiedadModel action = new GestionPropiedadModel();

        public ActionResult Index()
        {
            try
            {
                var propiedades = action.ListarPropiedades();
                Session["Propiedades"] = propiedades;

                // Verificar si la lista esta vacía
                if (propiedades.Count > 0)
                {
                    return View("Index", propiedades);
                }
                else
                {
                    return View("Index", new List<PropiedadV>());
                }
            }
            catch (Exception)
            {
                return View("~/Shared/Error.cshtml");
            }
        }

        [HttpGet]
        public ActionResult Propiedad(long id)
        {
            try
            {
                var propiedad = action.getPropiedad(id, (List<PropiedadV>)Session["Propiedades"]);
                if (propiedad == null)
                {
                    return View("Error");
                }
                else
                {
                    Session["idPropiedad"] = propiedad.Property.idPropiedad;
                    return View("Propiedad", propiedad);
                }
            }
            catch (Exception)
            {
                return View("Error");
            }
        }

        public ActionResult Logout()
        {
            Session.Abandon();
            Response.Cookies.Add(new HttpCookie("ASP.NET_SessionId", ""));
            return RedirectToAction("Index", "Home");
        }
    }
}

Bienes Raices HAXA/Views/Home/Index.cshtml
@model IEnumerable<Bienes_Raices_HAXA.Models.PropiedadV>
<!DOCTYPE html>
<html>
<head>
    <title>
        @{ ViewBag.Title = "Haxa Bienes Raices"; }
    </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @Styles.Render("~/Content/main.css")
    @Styles.Render("~/Content/shopify.css")
</head>

<body>
    <!-- Header -->
    <header class="w3-display-container w3-content w3-wide" style="max-width:700px;" id="home">
        <img class="w3-image" src="~/Content/images/Portada-bienes-raices.jpg" alt="Architecture" width="1400" height="400">
        <div class="w3-display-middle w3-margin-top w3-center">
            <h1 class="w3-xxlarge w3-text-white"><span class="w3-padding w3-black w3-opacity-min"><b>BR</b></span> <span class="w3-hide-small w3-text-light-grey">Haxa</span></h1>
        </div>
    </header>

    <!-- Page content -->
    <div class="w3-content w3-padding" style="max-width:1564px">

        <!-- Property Section -->
        <div class="w3-container" id="property">
            <h3 class="w3-border-bottom w3-border-light-grey" style="text-align:center;">Propiedades</h3>
        </div>

        <div class="w3-row-padding">
            <div class="boost-pfs-filter-products boost-pfs-filter-product-item-layout-no-border boost-pfs-filter-product-item-label-top_left boost-pfs-filter-product-item-swatch_color_display_type_image_product boost-pfs-filter-swatch-shape-circle boost-pfs-filter-product-item-text-alignment-left" style="min-height: 0px;">
                <!-- Todas las propiedades aqui -->
                @{int count = 1; @*int countEnd = 0;*@}
                <!--agregar datos a la bd-->
                @foreach (var item in Model)
                {
                <div class="boost-pfs-filter-product-item boost-pfs-filter-product-item-grid boost-pfs-filter-grid-width-3 boost-pfs-filter-grid-width-mb-1 has-bc-swap-image" data-id="6582722756704" data-page="@count">
                    <div class="boost-pfs-filter-product-item-inner">
                        <div class="boost-pfs-filter-product-item-image">
                            <a href="@Url.Action("Propiedad","Home",new {id=@item.Property.idPropiedad})" class="boost-pfs-filter-product-item-image-link" style="padding-top:100%;">
                                @{int lengthImg = item.Img.Count; }
                                @switch (lengthImg)
                    {

                        case 1:
                                <img class="boost-pfs-filter-product-item-main-image Image--lazyLoad lazyautosizes ls-is-cached lazyloaded"
                                     data-src="@item.Img[0].link"
                                     data-widths="[180,360,540,720,900,1080,1296,1512,1728,2048]" data-sizes="auto"
                                     src="@item.Img[0].link"
                                     alt="@item.Property.nombre" sizes="auto" />
                                <img class="boost-pfs-filter-product-item-flip-image Image--lazyLoad lazyautosizes ls-is-cached lazyloaded"
                                     data-src="@item.Img[0].link"
                                     data-widths="[180,360,540,720,900,1080,1296,1512,1728,2048]" data-sizes="auto"
                                     src="@item.Img[0].link"
                                     alt="@item.Property.nombre" sizes="auto" /> break;
                                                case 0:
                                <img class="boost-pfs-filter-product-item-main-image Image--lazyLoad lazyautosizes ls-is-cached lazyloaded"
                                     data-src="~/Content/images/Portada-bienes-raices.jpg"
                                     data-widths="[180,360,540,720,900,1080,1296,1512,1728,2048]" data-sizes="auto"
                                     src="~/Content/images/Portada-bienes-raices.jpg"
                                     alt="@item.Property.nombre" sizes="auto" />
                                <img class="boost-pfs-filter-product-item-flip-image Image--lazyLoad lazyautosizes ls-is-cached lazyloaded"
                                     data-src="~/Content/images/Portada-bienes-raices.jpg"
                                     data-widths="[180,360,540,720,900,1080,1296,1512,1728,2048]" data-sizes="auto"
                                     src="~/Content/images/Portada-bienes-raices.jpg"
                                     alt="@item.Property.nombre" sizes="auto" /> break;
                                                                        default:
                                <img class="boost-pfs-filter-product-item-main-image Image--lazyLoad lazyautosizes ls-is-cached lazyloaded"
                                     data-src="@item.Img[0].link"
                                     data-widths="[180,360,540,720,900,1080,1296,1512,1728,2048]" data-sizes="auto"
                                     src="@item.Img[0].link"
                                     alt="@item.Property.nombre" sizes="auto" />
                                <img class="boost-pfs-filter-product-item-flip-image Image--lazyLoad lazyautosizes ls-is-cached lazyloaded"
                                     data-src="@item.Img[1].link"
                                     data-widths="[180,360,540,720,900,1080,1296,1512,1728,2048]" data-sizes="auto"
                                     src="@item.Img[1].link"
                                     alt="@item.Property.nombre" sizes="auto" />break;
                                                                                            }
                            </a>
                            @*<div class="boost-pfs-filter-product-item-label">
                                    <span class="tag boost-pfs-filter-label tagblack-friday-2021">Oferta</span>

                                    <span class="tag boost-pfs-filter-label tagcon-obsequio">Destacada</span>
                                </div>*@
                        </div>

                        <div class="boost-pfs-filter-product-bottom">

                            <a href="@Url.Action("Propiedad","Home",new {id=item.Property.idPropiedad})" class="boost-pfs-product-item-manufacturer">@item.Property.nombre</a>
                            <a href="@Url.Action("Propiedad","Home",new {id=item.Property.idPropiedad})" class="boost-pfs-filter-product-item-title">@item.Property.descripcion</a>
                            <!-- <p class="boost-pfs-filter-product-item-vendor">Promadis S.A.</p> -->

                            <div class="testfreaks-item tf-item-tracked testfreaks-loaded" data-product-id="50SUC9300">
                                <div class="testfreaks-items">
                                    <div title="5.0 / 5" class="testfreaks">
                                        <div class="tf-stars tf-stars-svg">
                                            <div class="tf-stars-svg tf-stars-fg">
                                            </div>
                                        </div>
                                        <div class="tf-based">
                                            <div class="tf-count">@item.Property.m2 m2</div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <a href="@Url.Action("Propiedad","Home",new {id=item.Property.idPropiedad})">
                                <p class="boost-pfs-filter-product-item-price">
                                    <!--if descuento--> <!--<s><span class="money">₡381,900</span></s>--> <!--if descuento-->
                                    <span class="boost-pfs-filter-product-item-sale-price">
                                        <span class="money">@item.Property.precio</span>
                                    </span>
                                </p>
                            </a>
                        </div>
                    </div>
                </div>
                <!--if count % 3 = 0
                insrt otra linea
                -->}
            </div>
        </div>

        <!-- About Section -->
        <div class="w3-container w3-padding-32" id="about">
            <h3 class="w3-border-bottom w3-border-light-grey w3-padding-16">Acerca de HAXA</h3>
            <p>
                <!-- Todo Acerca de aqui -->
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Excepteur sint
                occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco
                laboris nisi ut aliquip ex ea commodo consequat.
            </p>
        </div>

        <!-- End page content -->
    </div>
</body>
</html>

Bienes Raices HAXA/Views/Home/Propiedad.cshtml
@model Bienes_Raices_HAXA.Models.PropiedadV
<!DOCTYPE html>
<html>
<head>
    <title>
        @{ ViewBag.Title = "Propiedades"; }
    </title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body, h1, h2, h3, h4, h5, h6 {
            font-family: "Raleway", Arial, Helvetica, sans-serif
        }

        .mySlides {
            display: none
        }
    </style>
    @Styles.Render("~/Content/main.css")
    @Styles.Render("https://fonts.googleapis.com/css?family=Raleway")
    @Styles.Render("https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css")
</head>
<body>
    <!-- Top menu on small screens -->
    <!-- !PAGE CONTENT! -->
    <div class="w3-main w3-white">

        <!-- Push down content on small screens -->
        <div class="w3-hide-large" style="margin-top:80px"></div>

        <!-- Slideshow Header -->
        <div class="w3-container" id="apartment">
            <h2 class="w3-text-green">@Model.Property.nombre</h2>
            @foreach (var item in Model.Img)
            {
            <div class="w3-display-container mySlides">
                <img src="@item.link" style="width:100%;margin-bottom:-6px">
            </div>      }
            <div class="w3-display-container mySlides">
                <img src="~/Content/images/Portada-bienes-raices.jpg" style="width:100%;margin-bottom:-6px">
            </div>
        </div>
        <div class="w3-row-padding w3-section">
            @foreach (var item in Model.Img)
            {
            <div class="w3-col s3">
                <img class="demo w3-opacity w3-hover-opacity-off" src="@item.link" style="width:100%;cursor:pointer" onclick="currentDiv(@item.link)">
            </div>      }
            <div class="w3-col s3">
                <img class="demo w3-opacity w3-hover-opacity-off" src="~/Content/images/Portada-bienes-raices.jpg" style="width:100%;cursor:pointer" onclick="currentDiv(~/Content/images/Portada-bienes-raices.jpg)">
            </div>
        </div>
        <div class="w3-container">

            @if (Model.Property.descripcion != null)
            {
            <h4><strong>Detalle</strong></h4>
            <div class="w3-row w3-large">
                <p>@Model.Property.descripcion</p>
            </div>}

            <hr>
            <h4><strong>Caracteristicas</strong></h4>
            <div class="w3-row w3-large">
                <div>
                    <p>M2= @Model.Property.m2</p>
                </div>
                <div class="w3-col s6">
                    @if (Model.Property.baños != null)
                    {
                    <p><i class="fa fa-fw fa-bath"></i> Baños: @Model.Property.baños</p>}
                    @if (Model.Property.habitacion != null)
                    {
                    <p><i class="fa fa-fw fa-bed"></i> Habitaciones: @Model.Property.habitacion</p>}
                </div>
                <div class="w3-col s6">
                    @if (Model.Property.pisos != null)
                    {
                    <p>Niveles: @Model.Property.pisos</p>}
                    @if (Model.Property.garage != null)
                    {
                    <p><i></i> Plazas de parqueo: @Model.Property.garage</p>}
                </div>
            </div>
            <hr>
        </div>
        <div class="w3-container">

            <h2>Citas</h2>

            @if (Session["id"] != null)
            {
            @Html.HiddenFor(x => x.Property.idPropiedad)
            <a class="btn btn-success" style="margin-bottom:10px" onclick=PopupForm1('@Url.Action("AgregarCita", "Citas" )')><i class="fa fa-plus"></i>Agregar cita</a> }
                    else
                    {
            <p>¡Inicia sesión para solictar una cita!</p>}
        </div>
    </div>
    <hr>
    <!-- Contact -->
    <div class="w3-container" id="contact">
        <h2>Contact</h2>
        <i class="fa fa-phone" style="width:30px"></i> Telefono: +506 8989-8989<br>
        <i class="fa fa-envelope" style="width:30px"> </i> Email: contacto@brhaxa.com<br>
    </div>
    <!-- End page content -->
    </div>

    <script>// Slideshow Apartment Images
        var slideIndex = 1;
        showDivs(slideIndex);

        function plusDivs(n) {
            showDivs(slideIndex += n);
        }

        function currentDiv(n) {
            showDivs(slideIndex = n);
        }

        function showDivs(n) {
            var i;
            var x = document.getElementsByClassName("mySlides");
            var dots = document.getElementsByClassName("demo");
            if (n > x.length) { slideIndex = 1 }
            if (n < 1) { slideIndex = x.length }
            for (i = 0; i < x.length; i++) {
                x[i].style.display = "none";
            }
            for (i = 0; i < dots.length; i++) {
                dots[i].className = dots[i].className.replace(" w3-opacity-off", "");
            }
            x[slideIndex - 1].style.display = "block";
            dots[slideIndex - 1].className += " w3-opacity-off";
        }</script>
</body>
</html>