Bienes Raices HAXA/Controllers/LogInController.cs
using Bienes_Raices_HAXA.Models;
using System.Web.Mvc;

namespace Bienes_Raices_HAXA.Controllers
{
    public class LogInController : Controller
    {
        public ActionResult Login()
        {
            if (Session["email"] != null)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }

        [HttpPost]
        public ActionResult validacionLogin(string email, string password)
        {
            Security model = new Security();

            var validacion = model.validarLogin(email, password);

            if (validacion != null)
            {
                Session["email"] = validacion.email;
                Session["rol"] = validacion.idRol;
                Session["id"] = validacion.idUsuario;
                return RedirectToAction("Index", "Home");
            }

            return View("~/Views/Shared/Error.cshtml");
        }
    }
}

Bienes Raices HAXA/Views/LogIn/LogIn.cshtml
<!DOCTYPE html>
<html>
<head>
    @{ ViewBag.Title = "Login"; }
    @Styles.Render("~/Content/Login.css")
</head>
<body>
    <br />
    <div class="login-block">

        <form action="@Url.Action("validacionLogin","LogIn")" method="post" class="signin">
            <img class="image" src="~/Content/images/Haxa_LOGO.jpeg" alt="Architecture" width="150" height="150">

            <h1>INGRESA TUS DATOS</h1>

            <div class="form-group">
                <br />
                <input type="text" name="email" value="" placeholder="Email" />
                <br />
                <input type="password" name="password" value="" placeholder="Contraseña" />

                <button class="button">Iniciar sesion</button>
            </div>
        </form>
    </div>
</body>
</html>